version: '3'

services:
  apache_php:
    build:
      context: './.docker/apache_php/'
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    volumes:
      - .docker/apache_php/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - .docker/apache_php/php.ini:/usr/local/etc/php/php.ini
      - .:/srv/app
    links:
      - mysql
  mysql:
    build:
      context: './.docker/mysql/'
      dockerfile: Dockerfile
    ports:
      - 43306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "221344"
    volumes:
      - .docker/mysql/db:/var/lib/mysql
      - .docker/mysql/dump:/tmp/dump
      - .docker/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf