CREATE DATABASE IF NOT EXISTS resume CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER IF NOT EXISTS 'resume'@'%' IDENTIFIED BY 'Qwerty123$';
GRANT ALL PRIVILEGES ON resume.* TO 'resume'@'%';
FLUSH PRIVILEGES;
